services:
  postgres:
    image: postgres:16-alpine
    container_name: remo_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: remo_tenants
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - remo_pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: remo_app
    restart: always
    environment:
      PORT: 5050
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgrespassword
      DB_NAME: remo_tenants
      JWT_SECRET: super-secret-jwt-key-for-remo-test
    ports:
      - "5050:5050"
    depends_on:
      - postgres

volumes:
  remo_pgdata:
