version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: remo_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: remo_tenants
    ports:
      - "5433:5432"
    volumes:
      - remo_pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  remo_pgdata:
